<template>
  <div>
    <div>
      <Newscarousel v-bind:items="itemsCarousel"/>
    </div>
    <div v-for="(item,i) in itemsCards" 
          :key="i">
      <NewsCard class="NewsCard" 
        v-bind:titre="item.titre"
        v-bind:auteur="item.auteur" 
        v-bind:contenu="item.contenu"
        v-bind:pic_name="item.pic_name"/>
    </div>
  </div>
</template>

<script>
import NewsCard from '../components/NewsCard'
import Newscarousel from '../components/CarouselNews'
export default {
  name: '',
  components: {   
    Newscarousel,
    NewsCard,
  },
  data () {
    return {
      itemsCarousel: [            
       {src: require('../assets/images/ImagesCarousel/Actualité/News11.jpeg'), titre: "D’abord la relance, ensuite l’équilibre budgétaire", contenu: "Selon le ministre des finances, le troisième budget du gouvernement caquiste vise à corriger les «vulnérabilités» dans les réseaux de la santé et de l'éducation mises en lumière par la pandémie."},
       {src: require('../assets/images/ImagesCarousel/Actualité/News21.jpeg'), titre: "Une aide pour les victimes de violence conjugale jugée insuffisante", contenu: "Comme promis, Québec a réservé des fonds dans son budget pour rehausser l’aide aux victimes de violence conjugale."},
       {src: require('../assets/images/ImagesCarousel/Actualité/News3.jpeg'), titre: "Ottawa devra mettre les bouchées doubles pour trouver les fraudeurs", contenu: "Des années seront nécessaires pour récupérer les montants d'aide d’urgence encaissés indûment, estime la VG."},
       {src: require('../assets/images/ImagesCarousel/Actualité/News41.jpeg'), titre: "Le fédéral incapable de vérifier le respect des quarantaines", contenu: "Près des deux tiers des voyageurs ont échappé à la surveillance de l’Agence de la santé publique."},
      ],
      itemsCards : [
      {pic_name:"Actualité/News1.jpeg", titre:"Le Mexique et le Guatemala coopèrent pour freiner les migrants.", auteur:"Publié le 28 mars 2021 à 14h59" ,contenu:"« Les réseaux de passeurs leur ont vendu [aux migrants, NDLR] l’illusion de pouvoir arriver à la frontière américaine sans aucun risque », a déclaré le commissaire mexicain chargé des migrations, Francisco Garduño, en dévoilant l’opération lancée samedi.                    « C’est pour cette raison que nous allons renforcer notre présence dans cet État [Chiapas, NDLR] afin d’éviter que des enfants et des adolescents soient utilisés comme “ passeports ” pour arriver à la frontière », a-t-il ajouté.                   L’État mexicain du Chiapas est à la frontière avec le Guatemala et les migrants venus du Honduras, du Salvador et du Guatemala y transitent avant d’entreprendre le long et périlleux voyage vers le nord, jusqu’à la frontière américaine."},
      {pic_name:"Actualité/News2.jpeg", titre:"(New York) La société d’investissement Archegos Capital est à l’origine de la vente, inhabituelle par son ampleur, de plus de 20 milliards de dollars d’actions d’une poignée d’entreprises à Wall Street en une seule journée, affirme dimanche l’agence Bloomberg.  ", auteur:"Publié le 28 mars 2021 à 14h01" ,contenu:"Cette société, qui gère la fortune de l’homme d’affaires Bill Hwang, s’est délestée massivement vendredi de parts détenues dans des entreprises américaines de médias et des sociétés chinoises cotées à la Bourse de New York, indique l’agence en citant des sources proches du dossier.  Ces actions ont été vendues « en bloc », c’est-à-dire en quantité importante à un prix différent de celui du marché, par les banques d’affaires Morgan Stanley et Goldman Sachs notamment. Une telle méthode est courante mais l’ampleur des transactions effectuées vendredi a surpris les courtiers.Ces opérations ont participé au fort repli des actions concernées. Les sociétés ViacomCBS et Discovery ont ainsi plongé d’environ 27 % vendredi tandis que les entreprises chinoises Baidu et Tencent ont perdu jusqu’à 15 % et 21 % en séance avant de se reprendre et de terminer près de l’équilibre.Selon le Financial Times, qui cite aussi des sources proches du dossier, Archegos Capital a été bousculé par la forte baisse à Wall Street plus tôt dans la semaine de ViacomCBS, dont il détenait beaucoup d’actions.  Ce repli a conduit un des courtiers d’Archegos à demander des fonds supplémentaires pour couvrir la dépréciation de cet investissement et in fine, a conduit Archegos à liquider certaines de ses positions."},
      {pic_name:"Actualité/News3.jpeg", titre:"Inondation à Saint-Félix-de-Valois.", auteur:"Publié le 28 mars 2021 à 10h30" ,contenu:"Des amoncellements de glace se sont formés dans le cours d’eau au cours de la nuit du 26 au 27 mars. Le tout a provoqué des inondations le long de la rivière dans le secteur allant du chemin de la Pointe-à-Roméo jusqu’au camping Aventure Sentinelle. La municipalité maintient sa surveillance des cours d’eau, « mais le risque de montée soudaine s’est dissipé avec le passage de l’embâcle », assure-t-on par communiqué. « Le point critique était vraiment hier avec la présence de glace, avec au moins 3 kilomètres d’embâcle. Il continue d’avoir une surveillance des cours d’eau étant donné que le débit est assez fort », a spécifié Mathieu Voghel-Robert directeur des communications de la municipalité de Saint-Félix-de-Valois. Dimanche, les autorités étaient « en mode nettoyage » et s’assuraient de l’accompagnement des sinistrés. Entre 50 et 60 résidants de la municipalité ont été évacués samedi avec l’aide de la Croix-Rouge. La situation s’est rétablie, mais certains ont dû passer la nuit hors de leur domicile. « Nous demandons aux résidents dont l’eau est montée au niveau des prises de courant, appareils de chauffage ou toute installation électrique de ne pas rétablir le courant eux-mêmes et de faire appel à un électricien », averti Pierre Beaudin, directeur du Service de protection et d’intervention d’urgence (SPIU).« La situation s’améliore, mais le risque de montée soudaine n’est pas terminé, nous demandons à tous les résidents évacués d’attendre l’autorisation du SPIU avant de regagner leur domicile », avait souligné samedi matin Audrey Boisjoly, mairesse de Saint-Félix-de-Valois.De fortes pluies prévues dimanche. D’abondantes précipitations sont prévues dans plusieurs régions au sud du Québec, où plusieurs alertes météorologiques ont été émises par Environnement Canada.En Beauce, en Estrie, en Mauricie, dans Lanaudière, dans les Laurentides, à Drummondville, à La Tuque et à Lachute, on estime qu’entre 25 à 40 millimètres de pluie tomberont dimanche en soirée. « Cette pluie pourrait contribuer à la hausse du niveau des cours d’eau », ajoute-t-on.À Gatineau, on parle de 20 à 30 millimètres de pluie touchant la région de la capitale nationale et le couloir de l’autoroute 417.Les précipitations doivent débuter dimanche après-midi dans ce secteur.« Les pluies torrentielles peuvent entraîner une accumulation d’eau sur les routes et réduire la visibilité. Des inondations sont aussi possibles par endroits dans les basses-terres », selon Environnement Canada. "},
      {pic_name:"Actualité/News4.jpeg", titre:"Le premier ministre François Legault a mis en vente sa maison d’Outremont, au prix de 5 millions de dollars.", auteur:"Publié le 27 mars 2021 à 0h15" ,contenu:"« Cette magnifique demeure victorienne est sise sur un incroyable lot de 18 000 pieds carrés avec piscine creusée chauffée », huit chambres à coucher, cinq salles de bain, un solarium, des salles de réception et trois stationnements intérieurs, peut-on lire dans la fiche descriptive du courtier immobilier Joseph Montanaro. François Legault a l’intention de « rester à Montréal, mais il veut quelque chose de plus petit », explique son directeur des relations médias, Manuel Dionne. Le prix demandé s’élève très précisément à 4,995 millions. En 2015, le chef caquiste et sa femme, Isabelle Brais, avaient déjà tenté de vendre leur demeure à un prix semblable, 4,9 millions. On rapportait alors que le couple avait payé 1,15 million pour cette maison en 1998, selon le dernier acte de vente de la propriété. Le cofondateur d’Air Transat faisait son entrée en politique la même année, dans le gouvernement péquiste de Lucien Bouchard. La valeur de la résidence s’élève à 5,4 millions, d’après le rôle d’évaluation foncière."},
      {pic_name:"Actualité/News5.jpeg", titre:"Une élue conservatrice fustige le jugement sur la tarification du carbone.", auteur:"Publié le 26 mars 2021 à 18h15" ,contenu:"Dans une vidéo publiée sur Twitter, vendredi en fin d’après-midi, la représentante du Parti conservateur pour la circonscription de Calgary Midnapore, en Alberta, a dit toute son insatisfaction par rapport au verdict du plus haut tribunal au pays. « La Cour suprême a jugé que la taxe carbone n’est pas inconstitutionnelle. Eh bien j’ai quelques questions pour la Cour suprême du Canada », lance-t-elle en ouverture de cette vidéo d’une durée de 40 secondes, en attribuant erronément le dépôt de la décision à « aujourd’hui » (vendredi) alors qu’il remonte à jeudi. « Le droit de gagner sa vie est-il inconstitutionnel ? Le droit de mettre de la nourriture sur la table est-il inconstitutionnel ? Détruire une province est-il inconstitutionnel ? Détruire une région est-il inconstitutionnel ? Détruire une industrie au complet est-il inconstitutionnel ? », énumère Mme Kusie. « Je pense que ça l’est », tranche la députée albertaine, invitant ses abonnés à relayer son message. Parmi ceux qui ont partagé la vidéo figure le groupe de droite Canada Proud, dont l’un des fondateurs est Jeff Ballingall, un membre de l’entourage du chef conservateur Erin O’Toole. Le capitaine des troupes conservatrices a lui aussi regretté le jugement majoritaire (six juges contre trois) de la Cour suprême du Canada. S’il n’est pas allé aussi loin dans ses déclarations, il a cependant réaffirmé son intention d’abolir la tarification du carbone en cas de victoire au prochain scrutin. Le plus haut tribunal au pays a tranché jeudi en faveur du gouvernement fédéral dans cette cause qui avait été portée à son attention par les gouvernements de l’Ontario, de la Saskatchewan et de l’Alberta, dont les premiers ministres sont opposés à la mesure. « La [Loi sur la tarification de la pollution causée par les gaz à effet de serre] est constitutionnelle. Elle fixe, en vue de réduire les émissions de GES, des normes nationales minimales de tarification rigoureuse de ces gaz. Le Parlement a compétence pour adopter cette loi en tant que matière d’intérêt national », a-t-il conclu. La semaine qui s’achève a été marquée par les enjeux environnementaux pour le Parti conservateur. Il y a eu ce jugement d’importance, mais auparavant, la question des changements climatiques avait plongé le chef de la formation dans l’embarras. Lors du congrès virtuel du parti, samedi dernier, 54 % des délégués ont défait une motion reconnaissant que « les changements climatiques sont réels ». Le chef O’Toole a par la suite mis son pied à terre et insisté que c’était lui qui était aux commandes, et qu’il présenterait un plan de lutte contre les changements climatiques."}
      ]
    } 
  },
}
</script>

<style>
.NewsCard {
  margin: 20px;
}
</style>
