<template>
  <div>
    <div v-for="(item,i) in itemsCards" 
          :key="i">
      <NewsCard class="NewsCard" 
        :titre="item.titre"
        :auteur="item.auteur" 
        :contenu="item.contenu"
        :pic_name="item.pic_name"/>
    </div>
  </div>
</template>

<script>
import NewsCard from '../components/CardNews'
export default {
  name: '',
  components: {   
    NewsCard,
  },
  data () {
    return {
      itemsCards : [
      {pic_name:"Sport/News1.jpeg", titre:"Un premier match reporté dans le Baseball majeur.", auteur:"Publié le 28 mars 2021 à 14h59", contenu:"Les Nationals de Washington ont indiqué en début d’après-midi que leur duel prévu en soirée contre les Mets de New York a été reporté à une date ultérieure en raison « du traçage de contacts d’un membre de l’organisation ». L’équipe n’a pas donné plus de détail, outre que par « abondance de précaution », cette rencontre ne sera pas reprise vendredi, alors que les deux clubs devaient avoir congé. Le directeur général des Nationals, Mike Rizzo, a déclaré mercredi que l’un des joueurs de l’équipe avait subi un test positif au coronavirus lundi, avant que l’équipe ne quitte son site d’entraînement. Rizzo a ajouté que quatre autres joueurs et un membre du personnel se sont soumis aux protocoles de quarantaine après que le traçage de contacts eut déterminé qu’ils avaient eu des contacts rapprochés avec le joueur dont le test est positif. Le DG n’a pas identifié les gens concernés. « Nous sommes toujours en train de déterminer quel est exactement leur statut, avait déclaré Rizzo mercredi. Ils ne seront assurément pas du match de (jeudi). » Les champions de la Série mondiale de 2019, qui ont terminé à égalité au dernier rang dans l’Est de la Nationale en 2020, devaient envoyer Max Scherzer au monticule pour un duel de gagnants de cinq Cy-Young face à Jacob deGrom. Les Nationals ont appris le résultat positif un peu après 1 h dans la nuit de mardi à mercredi. C’est pendant le vol entre la Floride et Washington que les contacts rapprochés ont eu lieu entre le joueur infecté et les quatre autres membres du club. Scherzer a indiqué qu’il n’avait pas pris ce vol, préférant faire le trajet avec sa famille. Aucun joueur des Nationals n’avait subi un test positif au cours des six semaines du camp d’entraînement. « Nous avions si bien fait pendant le camp, a dit Scherzer. Partout d’ailleurs : il y a eu si peu de cas pendant le camp d’entraînement. Ça prouve à quel point la situation peut rapidement changer. ». Rizzo a précisé que l’équipe s’est soumise à une nouvelle ronde de tests mercredi, tel qu’il était déjà prévu. Les joueurs se sont soumis à une combinaison de tests rapides et de tests de la salive, prescrits par la MLB. Un premier duel, celui entre les Orioles de Baltimore et les Red Sox, avait été remis plus tôt jeudi, mais en raison de la pluie qui sévissait à Boston."},
      {pic_name:"Sport/News2.jpeg", titre:"Les Sénateurs s’entendent avec Jacob Bernard-Docker.", auteur:"Publié le 1er avril 2021 à 11h08" ,contenu:"Après avoir respecté sa quarantaine, Bernard-Docker se rapportera aux Sénateurs. L’Albertain a été un choix de premier tour, 26e au total au repêchage de 2018. Son équipe de l’Université du Dakota du Nord vient d’être éliminée du tournoi de fin de saison de la NCAA en cinquième période de prolongation, pavant la voie au début de sa carrière professionnelle. Bernard-Docker a marqué trois buts et ajouté 15 aides en 27 rencontres cette saison, au terme de laquelle il a été élu défenseur par excellence de la NCHC."},
      {pic_name:"Sport/News3.jpeg", titre:"La classique Paris-Roubaix reportée à l’automne", auteur:"Publié le 1er avril 2021 à 10h33" ,contenu:"L’an dernier, l’épreuve avait déjà été reportée à l’automne et finalement annulée, pour le même motif. Tant la course masculine créée en 1896 que la version féminine qui devait avoir lieu pour la première fois.  Depuis la première édition à la fin du XIXe siècle, seules les deux guerres mondiales ont eu raison de Paris-Roubaix, entre 1915 et 1918 puis entre 1940 et 1942 avant que la COVID-19 fasse son œuvre.  Les nouvelles dates, le 2 octobre pour la course des dames et le 3 octobre pour la course des messieurs, ont été ratifiées à l’unanimité par le Conseil du cyclisme professionnel (CCP), réuni jeudi par le président de l’UCI David Lappartient.  L’hypothèse d’un report ou d’une annulation avait pris corps dès le début de la semaine dernière quand le préfet des Hauts-de-France Michel Lalande l’avait publiquement évoquée.  Dans la continuité du tour de vis décidé mercredi par le président de la République Emmanuel Macron, au vu de la situation sanitaire, le préfet a tranché jeudi, à dix jours du rendez-vous qui devait être donné à Compiègne (Oise), lieu traditionnel du départ.  La « reine des classiques », dont la dernière édition a été remportée en avril 2019 par le Belge Philippe Gilbert, prendra donc place dans le calendrier une semaine après le championnat du monde prévu à Louvain (Belgique)."},
      {pic_name:"Sport/News4.jpeg", titre:"Philippe Langevin : « Je peux dire que je suis revenu à 100 % »", auteur:"Publié le 1er avril 2021 à 10h28" ,contenu:"L’athlète de 19 ans n’avait pas d’objectif précis à son arrivée en Suisse à seulement quelques jours de l’épreuve de slopestyle de Silvaplana. Sa dernière présence dans le circuit international remontait à novembre 2020, à Stubai, en Autriche. Mais le moins que l’on puisse dire, c’est qu’il était à sa place avec l’élite, comme en témoigne son neuvième rang dans sa vague de qualification, à un échelon d’un billet pour la finale. « Juste d’avoir manqué la finale par un point, ça me fait dire que je fais encore partie de la game. En plus, c’est assez incroyable comment le sport a évolué en deux ans. Je suis vraiment content », a résumé à Sportcom celui qui n’a pris part qu’à deux compétitions depuis 2019.S’il a accepté ce défi de dernière minute, c’est parce qu’il se sentait prêt à le relever. Après un séjour fructueux dans l’Ouest canadien, il a pu ajouter deux jours d’entraînement au centre Maximise à Sainte-Agathe pour mettre une touche finale à sa préparation et partir vers l’Europe avec confiance.« Cet hiver, je n’étais pas censé compétitionner, a-t-il précisé. Je devais juste m’entraîner pour être prêt pour la saison prochaine. J’ai su qu’il y avait une place deux jours avant de partir. Mon coach m’a appelé vers 22 heures pour me dire de faire mes valises. »Cette pause devait lui permettre de revenir après une blessure à un pied et de reprendre confiance sur ses skis.« Aussi, en décembre, j’ai fait une petite chute. Mon ski s’est décroché sur une rampe et je suis tombé sur une épaule. Je me suis déchiré un ligament et ça m’a mis à l’écart pendant un mois, mais j’ai fait de la physio en malade, a-t-il raconté. Je me suis entraîné et en ce moment, je suis super content de comment je skie. Je peux dire que je suis revenu à 100 %. »De retour au Québec la fin de semaine dernière, Philippe Langevin veut poursuivre sur sa lancée et il est impatient de reprendre l’action à Whistler avec ses coéquipiers dès que sa quarantaine obligatoire sera complétée. Il se préparera en vue des étapes de qualification olympique à venir dans une année 2021 qui pourrait être bien remplie."},
      {pic_name:"Sport/News5.jpeg", titre:"En route vers les ligues majeures.", auteur:"Publié le 1er avril 2021 à 7h00" ,contenu:"Le Dominicain est débarqué à Montréal à 11 ans, en 2010. « J’étais un enfant. Je ne savais pas trop ce qui se passait. C’était un peu dur pour moi à cause de la langue et de toutes les autres différences », se souvient-il. En République dominicaine, il vivait avec sa grand-mère. Sa mère travaillait aux États-Unis, tandis que son père habitait le Québec depuis longtemps, avec ses enfants nés d’une autre union. Puis, le paternel, camionneur, s’est séparé et a fait venir Otto à Montréal, afin qu’il y fasse ses études. Sa mère a alors aussi pris le chemin de la métropole. « Ça faisait longtemps que je n’avais pas vu mon père. Il voulait qu’on soit tous ensemble. On s’est tous rassemblés. C’était comme une réconciliation qu’on a faite », raconte le baseballeur, qui est actuellement à Dunedin, en Floride. Ce renouement familial, ces moments passés avec ses proches ont grandement facilité l’acclimatation à sa nouvelle vie. Bien que, pour la communication, il a fallu un peu de temps. « Avec mes neveux, ç’a été familier tout de suite. Mais ils parlaient tous français, j’étais le seul qui ne comprenait rien ! C’était un peu dur, mais ils m’ont aidé et je l’ai appris assez vite. Je dirais qu’en moins d’un an, je pouvais parler pas mal avec les autres. ». López est désormais trilingue. Et puis, il y a eu le classique météorologique. Après quelques mois, il a compris pourquoi nombre de ses nouveaux concitoyens prenaient annuellement un vol en sens inverse…"}
      ]
    } 
  },
}
</script>

<style>
.NewsCard {
  margin: 20px;
}
</style>
